INSERT INTO review (customer_id, menu_id, rating, comment) VALUES
(1, 1, 4, 'Great pizza!'),
(2, 2, 5, 'Delicious burger!'),
(3, 3, 4, 'Tasty pasta.'),
(1, 1, 3, 'Pizza was okay.'),
(2, 2, 4, 'The burger was fantastic!'),
(3, 3, 3, 'Pasta could have been better.'),
(1, 2, 5, 'Best burger ever!'),
(2, 3, 4, 'Enjoyed the pasta.'),
(3, 1, 4, 'Pizza was delicious.'),
(1, 3, 5, 'Amazing pasta dish!'),
(2, 1, 3, 'Pizza was average.'),
(3, 2, 4, 'The burger was tasty.'),
(1, 2, 4, 'Good burger.'),
(2, 3, 5, 'Pasta was excellent!'),
(3, 1, 5, 'Loved the pizza!'),
(1, 3, 3, 'Pasta was okay.'),
(2, 1, 4, 'Great pizza!'),
(3, 2, 3, 'Burger was decent.'),
(1, 2, 5, 'Fantastic burger!'),
(2, 3, 4, 'Enjoyed the pasta.');
